# 7 - Filtragem de dados
Filtragem de dados é uma tarefa importantíssima na vida de qualquer cientista de dados. Nessa seção, veremos como criar filtros em um conjunto de dados utilizando o Pandas.

## Operadores booleanos

### and

Simples verificação lógica para verificar se x está em um intervalo de interesse.

In [14]:
x = 12

In [15]:
x > 5 and x < 15

True

### or

Mais uma verificação, porém aqui basta que uma das condições seja atendida.

In [16]:
y = 5

In [17]:
y < 7 or y > 13

True

### not

Invertendo um valor lógico.

In [18]:
not True

False

In [19]:
not False

True

### Numpy

Cria dois arrays e preenche com valores de ponto flutuante.

In [20]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

Multiplas verificações sob o vetor bmi.

In [21]:
bmi > 21

array([ True, False,  True,  True,  True])

In [22]:
bmi.all() > 21 and bmi.all() < 22

False

In [23]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

In [24]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.85171573, 21.75028214, 21.44127836])

## Filtrando um DataFrame Pandas

In [25]:
import pandas as pd
brics = pd.read_csv('brics.csv', index_col=0)
brics

FileNotFoundError: ignored

**Objetivo**: selecionar os países com área maior do que 8 milhões de km2

3 passos:
- Selecionar a coluna "area"
- Fazer uma comparação na coluna "area"
- Usar o resultado para selecionar os países

In [ ]:
# Selecionar a coluna "area"
brics['area']

Arranja em um novo vetor todos os valores que correspondem a verificação feita na segunda linha.

In [ ]:
# Fazer uma comparação na coluna "area"
brics['area'] > 8
is_huge = brics['area'] > 8
is_huge

In [ ]:
# Usar o resultado para selecionar os países
brics[is_huge]

In [ ]:
# Importando dataset de carros
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)
cars

In [ ]:
# Extraia a coluna 'drives_right' do DataFrame 'cars' e atribua a variável 'dr'
dr = cars['drives_right']

# Use a variável 'dr' para criar um subconjunto de dados chamado 'sel'
sel = cars[dr]

# Imprima a variável 'sel'
print(sel)

In [ ]:
# Crie uma variável car_maniac: linhas que possuem 'cars_per_cap' maiores do que 500
cpc = cars['cars_per_cap']
many_cars = cpc > 500
car_maniac = cars[many_cars]

# Imprima 'car_maniac'
print(car_maniac)

In [ ]:
# Importe o conjunto de dados 'cars.csv', bem como as bibliotecas 'pandas' e 'numpy'
import pandas as pd
import numpy as np
cars = pd.read_csv('cars.csv', index_col = 0)

# Crie a variável 'medium': linhas que possuem 'cars_per_cap' entre 100 e 500
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]

# Imprima 'medium'
print(medium)